Enhance Docker image validation in workflow
Added validation for image layer count and modified failure action handling.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,7 +9,8 @@ on:
 
 env:
   IMAGE_NAME: githubaction
-  FAIL_ON_IMAGE_SIZE: false
+  VALIDATION_FAILURE_ACTION: SUCCEED #or FAILURE SUCCEED
+  MAX_ALLOWED_IMAGE_LAYERS: 15
 
 jobs:
 
@@ -85,7 +86,7 @@ jobs:
           if [ "$IMAGE_SIZE_MB" -gt 500 ]; then
             echo "WARNING: Docker image size exceeds 500MB"
 
-            if [ "${{ env.FAIL_ON_IMAGE_SIZE }}" = "true" ]; then
+            if [ "${{ env.VALIDATION_FAILURE_ACTION }}" = "FAILURE" ]; then
               exit 1
             fi
           fi
@@ -102,8 +103,27 @@ jobs:
 
       - name: Show Docker Layers
         run: |
-          docker history \
-          ${{ secrets.DOCKER_AAYU_NAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
+          LAYERS=$(docker inspect ${{ secrets.DOCKER_AAYU_NAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }} | jq .[].RootFS.Layers | wc -l)
+          IMAGE_LAYER=$(expr $LAYERS - 2)
+          
+          echo "Number of Layers in image are $IMAGE_LAYER"
+          echo "Number of Layers are allowed is $MAX_ALLOWED_IMAGE_LAYERS"
+          
+          if [[ $IMAGE_LAYER -gt $MAX_ALLOWED_IMAGE_LAYERS ]]
+          then
+             if [[ $VALIDATION_FAILURE_ACTION == "FAILURE" ]]
+             then
+                  echo "Number of layers are more then expected layers count"
+                  echo "build unsucessfull"
+                  exit 1
+          
+             else
+                  echo "Number of layers are more then expected layers count please check!!!!!"
+             fi
+          else
+                  echo "Number of layers in docker image is  under expected layers count"
+                  logInfoMessage "build sucessfull"
+          fi
 
       - name: Push Docker Image
         run: |
